FROM 192.168.33.2/micro-service/openjdk:7-jre
MAINTAINER hunk huangkuier@gamil.com

COPY target/course-dubbo-service-1.0-SNAPSHOT.jar /course-dubbo-service.jar

ENTRYPOINT ["java", "-jar", "/course-dubbo-service.jar"]