FROM centos
ENV name Docker
# hunk/centos-entrypoint-shell
# docker build -t hunk/centos-entrypoint-shell .
# docker run hunk/centos-entrypoint-shell
# docker run -it hunk/centos-entrypoint-shell /bin/bash
#ENTRYPOINT echo "hello $name"

# hunk/centos-entrypoint-exec
# docker build -t hunk/centos-entrypoint-exec .
# docker run hunk/centos-entrypoint-exec
#ENTRYPOINT ["/bin/bash", "-c", "echo hello $name"]

# hunk/centos-cmd-shell
# docker build -t hunk/centos-cmd-shell .
# docker run hunk/centos-cmd-shell
# docker run -it hunk/centos-cmd-shell  /bin/bash
CMD echo "hello $name"



