--- 表达式
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hunkier.
--- DateTime: 2021/5/28 17:12
--- 算术运算符
--Lua 的算术运算符如下表所示：
--
--算术运算符	说明
--+	加法
---    减法
--*	乘法
--/	除法
--^	指数
--%	取模

print("-----------算术运算符-----------")
print( 1 + 2)
print(5/10)    ---> 打印 0.5
print(5.0/10)  ---> 打印 0.5
--print(10/0)  ---> 注意除数不能为零
print(2 ^ 10)  ---> 打印 1024。 求 2 的 10 次方
