// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package cn.hunkier.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.hunk.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .cn.hunk.proto.StudentResponse StudentResponse = 1;</code>
   */
  java.util.List<cn.hunkier.proto.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .cn.hunk.proto.StudentResponse StudentResponse = 1;</code>
   */
  cn.hunkier.proto.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .cn.hunk.proto.StudentResponse StudentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .cn.hunk.proto.StudentResponse StudentResponse = 1;</code>
   */
  java.util.List<? extends cn.hunkier.proto.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .cn.hunk.proto.StudentResponse StudentResponse = 1;</code>
   */
  cn.hunkier.proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
