Vagrant.require_version ">= 1.6.0"

boxes = [
    {
        :name => "master",
        :eth1 => "192.168.33.200",
        :mem => "3074",
        :cpu => "1",
        :fp => "22"
    },
    {
        :name => "worker1",
        :eth1 => "192.168.33.201",
        :mem => "3074",
        :cpu => "1",
        :fp => "23"
    },
    {
        :name => "worker2",
        :eth1 => "192.168.33.202",
        :mem => "3074",
        :cpu => "1",
        :fp => "24"
    },
    {
        :name => "worker3",
        :eth1 => "192.168.33.203",
        :mem => "1024",
        :cpu => "1",
        :fp => "25"
    }

]

Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.provider "vmware_fusion" do |v|
        v.vmx["memsize"] = opts[:mem]
        v.vmx["numvcpus"] = opts[:cpu]
      end
      config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", opts[:mem]]
        v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
      end
      config.vm.network :private_network, ip: opts[:eth1]
      config.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", disabled: "true"
      config.vm.network "forwarded_port", guest: 22, host: opts[:fp]
    end
  end
  config.vm.synced_folder "./labs", "/home/vagrant/labs"
  config.vm.provision "shell", privileged: true,  path:"./setup.sh"
end
