# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### 发送手机验证码
POST http://localhost:8082/user/sendVerifyCode
Accept: */*
Content-Type: application/x-www-form-urlencoded

mobile=18812345678

### 发送邮箱验证码
POST http://localhost:8082/user/sendVerifyCode
Accept: */*
Content-Type: application/x-www-form-urlencoded

email=805015788@qq.com

### 注册
POST http://localhost:8082/user/register
Accept: */*
Content-Type: application/x-www-form-urlencoded

username=hunk&password=123456&mobile=18812345678&email=805015788@qq.com&realName=hunk&verifyCode=


### 登录
POST http://localhost:8082/user/login
Accept: */*
Content-Type: application/x-www-form-urlencoded

username=hunk&password=123456

#username=lilei&password=123456

### 获取用户信息
POST http://localhost:8082/user/authentication
Accept: */*
token: bxc4nazmlouyg5mgc248507jj77pqzfo
Content-Type: application/x-www-form-urlencoded


###



